
development:
  adapter: postgresql
  encoding: unicode
  database: oliviaifergan_store_development_db
  pool: 5
  username: olivia_ifergan
  password:
  host: localhost

production:
  adapter: postgresql
  database: <%= ENV['PG_DB'] %>
  encoding: unicode
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PW'] %>
  host: <%= ENV['PG_HOST'] %>
  port: <%= ENV['PG_PORT'] %>

test:
  adapter: postgresql
  database: oliviaifergan_store_test_db
  encoding: unicode
  username: olivia_ifergan
  password:
  host: localhost


